### ISSUE TITLE
FYI The Images Do Not Render

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [pytorch-labs/applied-ai#14]

**Comment by lessw2020** [comment]
Hi @robertgshaw2-neuralmagic  - thanks for flagging! 
I've uploaded the images to the repo itself instead of the incorrect links back to my own repo and this appears to render now when viewing on external device (vs failing earlier).
It should thus be fixed.  Please re-open if you find that is not the case, but in testing here it has been corrected.
Thanks again for reporting this!

**Comment by robertgshaw2-neuralmagic** [comment]
LGTM - working on adding these to vllm
